### ISSUE TITLE
Track configuration contains improperly locked exercises

### ISSUE THREAD

**Issue by nywilken** [exercism/delphi#219]
In the upcoming release of [Configlet v3.8.0](https://github.com/exercism/configlet/issues/121), the lint command will now verify that locked exercises meet the unlocked_by criteria, as defined by the track [configuration spec](https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md):

- Core exercises can not be unlocked by other exercises.
- Non-core exercises can only be unlocked by core exercises.

Before cutting a release of Configlet I am opening issues on all tracks found to contain one or more unlocked_by violations so that maintainers of the track can validate and remedy the violations.

```

-> The exercise 'isbn-verifier' is being unlocked by a non-core exercise. Non-core exercises can only be unlocked by core exercises.
```

**Comment by rpottsoh** [comment]
@nywilken thanks for updating `lint` which makes finding this problem very easy.  `tree` has been my best go to tool and with this error in config.json `isbn-verifier` doesn't even appear in the tree.

`two-fer`, `reverse-string`, and `bob` appear as bonus exercises after the tree.

Thanks again for improving `lint` and for pointing out the offending exercise in the Delphi track's configuration.  I was planning to just use the new `lint` to find the error (I monitor the configlet repo) instead of trying to figure out the problem manually; thanks for including in this issue where the problem lives.  :+1:
