### ISSUE TITLE
Remove obsolete version tracking assertions in exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/delphi#268]
Some tracks have added assertions to the exercise test suites that ensure that the solution has a hard-coded version in it.
In the old version of the site, this was useful, as it let commenters see what version of the test suite the code had been written against, and they wouldn't accidentally tell people that their code was wrong, when really the world had just moved on since it was submitted.

If this track does not have any assertions that track versions in the exercise tests, please close this issue.

If this track _does_ have this bookkeeping code, then please remove it from all the exercises.

See https://github.com/exercism/exercism/issues/4266 for the full explanation of this change.

**Comment by rpottsoh** [comment]
I have the version noted in each test suite,however no assertions are made against it.  It is simply there for my benefit, so I can easily tell at a quick glance if my test suite is up to date with canonical data for the exercise in problem-specifications.

Students should be able to update their copy of a test suite.  Test suites are improved all the time so students should be able to (easily) update to the new suite.  This means they need to be informed that an update is available.  I understand there is an issue open regarding unpinning and repinning.  This sounds fine.  Students need to be made aware that an updated test suite is available.  Will the site allow them to upgrade, or will the CLI be updated to allow the upgrade to occur.

Since I am not actively doing any thing with version value I store in each suite (it is for me) I am not planning to take any action on this issue.

**Comment by kytrinyx** [comment]
Having the versions without an assertion is totally fine!

I'll close this.

> Students need to be made aware that an updated test suite is available. Will the site allow them to upgrade, or will the CLI be updated to allow the upgrade to occur?

We have an open feature request about this, but haven't had the product discussion yet about implementation.
